USE [master]
GO
/****** Objeto: Database [QualityDocDB] Fecha de script: 02/05/2026 05:39:35 p. m. ******/
CREATE DATABASE [QualityDocDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'QualityDocDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL17.SQLEXPRESS02\MSSQL\DATA\QualityDocDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'QualityDocDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL17.SQLEXPRESS02\MSSQL\DATA\QualityDocDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [QualityDocDB] SET COMPATIBILITY_LEVEL = 170
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [QualityDocDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [QualityDocDB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [QualityDocDB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [QualityDocDB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [QualityDocDB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [QualityDocDB] SET ARITHABORT OFF 
GO
ALTER DATABASE [QualityDocDB] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [QualityDocDB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [QualityDocDB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [QualityDocDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [QualityDocDB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [QualityDocDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [QualityDocDB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [QualityDocDB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [QualityDocDB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [QualityDocDB] SET  ENABLE_BROKER 
GO
ALTER DATABASE [QualityDocDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [QualityDocDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [QualityDocDB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [QualityDocDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [QualityDocDB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [QualityDocDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [QualityDocDB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [QualityDocDB] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [QualityDocDB] SET  MULTI_USER 
GO
ALTER DATABASE [QualityDocDB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [QualityDocDB] SET DB_CHAINING OFF 
GO
ALTER DATABASE [QualityDocDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [QualityDocDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [QualityDocDB] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [QualityDocDB] SET OPTIMIZED_LOCKING = OFF 
GO
ALTER DATABASE [QualityDocDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [QualityDocDB] SET QUERY_STORE = ON
GO
ALTER DATABASE [QualityDocDB] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [QualityDocDB]
GO
/****** Objeto: Table [dbo].[ApprovalHistory] Fecha de script: 02/05/2026 05:39:35 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ApprovalHistory](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[DocumentId] [uniqueidentifier] NOT NULL,
	[UserId] [int] NOT NULL,
	[Action] [varchar](50) NOT NULL,
	[Comment] [text] NULL,
	[ActionDate] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Objeto: Table [dbo].[Companies] Fecha de script: 02/05/2026 05:39:35 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Companies](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](100) NOT NULL,
	[IsActive] [bit] NULL,
	[CreatedAt] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[Name] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Objeto: Table [dbo].[Documents] Fecha de script: 02/05/2026 05:39:35 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Documents](
	[Id] [uniqueidentifier] NOT NULL,
	[ParentId] [uniqueidentifier] NULL,
	[VersionNumber] [int] NULL,
	[IsLatest] [bit] NULL,
	[Title] [varchar](200) NOT NULL,
	[Description] [text] NULL,
	[FilePath] [varchar](500) NULL,
	[AuthorId] [int] NOT NULL,
	[StatusId] [int] NOT NULL,
	[CompanyId] [int] NOT NULL,
	[CreatedAt] [datetime] NULL,
	[SyncPostgre] [bit] NULL,
	[SyncFirebase] [bit] NULL,
	[LastErrorLog] [text] NULL,
	[DocumentCode] [varchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Objeto: Table [dbo].[DocumentStatus] Fecha de script: 02/05/2026 05:39:35 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DocumentStatus](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](50) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[Name] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Objeto: Table [dbo].[Roles] Fecha de script: 02/05/2026 05:39:35 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Roles](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](50) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[Name] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Objeto: Table [dbo].[Users] Fecha de script: 02/05/2026 05:39:35 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Users](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[FullName] [varchar](100) NOT NULL,
	[Email] [varchar](100) NOT NULL,
	[PasswordHash] [varchar](256) NOT NULL,
	[RoleId] [int] NOT NULL,
	[CompanyId] [int] NULL,
	[IsActive] [bit] NULL,
	[CreatedAt] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[Email] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ApprovalHistory] ADD  DEFAULT (getdate()) FOR [ActionDate]
GO
ALTER TABLE [dbo].[Companies] ADD  DEFAULT ((1)) FOR [IsActive]
GO
ALTER TABLE [dbo].[Companies] ADD  DEFAULT (getdate()) FOR [CreatedAt]
GO
ALTER TABLE [dbo].[Documents] ADD  DEFAULT (newid()) FOR [Id]
GO
ALTER TABLE [dbo].[Documents] ADD  DEFAULT ((1)) FOR [VersionNumber]
GO
ALTER TABLE [dbo].[Documents] ADD  DEFAULT ((1)) FOR [IsLatest]
GO
ALTER TABLE [dbo].[Documents] ADD  DEFAULT (getdate()) FOR [CreatedAt]
GO
ALTER TABLE [dbo].[Documents] ADD  DEFAULT ((0)) FOR [SyncPostgre]
GO
ALTER TABLE [dbo].[Documents] ADD  DEFAULT ((0)) FOR [SyncFirebase]
GO
ALTER TABLE [dbo].[Users] ADD  DEFAULT ((1)) FOR [IsActive]
GO
ALTER TABLE [dbo].[Users] ADD  DEFAULT (getdate()) FOR [CreatedAt]
GO
ALTER TABLE [dbo].[ApprovalHistory]  WITH CHECK ADD FOREIGN KEY([DocumentId])
REFERENCES [dbo].[Documents] ([Id])
GO
ALTER TABLE [dbo].[ApprovalHistory]  WITH CHECK ADD FOREIGN KEY([UserId])
REFERENCES [dbo].[Users] ([Id])
GO
ALTER TABLE [dbo].[Documents]  WITH CHECK ADD FOREIGN KEY([AuthorId])
REFERENCES [dbo].[Users] ([Id])
GO
ALTER TABLE [dbo].[Documents]  WITH CHECK ADD FOREIGN KEY([CompanyId])
REFERENCES [dbo].[Companies] ([Id])
GO
ALTER TABLE [dbo].[Documents]  WITH CHECK ADD FOREIGN KEY([ParentId])
REFERENCES [dbo].[Documents] ([Id])
GO
ALTER TABLE [dbo].[Documents]  WITH CHECK ADD FOREIGN KEY([StatusId])
REFERENCES [dbo].[DocumentStatus] ([Id])
GO
ALTER TABLE [dbo].[Users]  WITH CHECK ADD FOREIGN KEY([CompanyId])
REFERENCES [dbo].[Companies] ([Id])
GO
ALTER TABLE [dbo].[Users]  WITH CHECK ADD FOREIGN KEY([RoleId])
REFERENCES [dbo].[Roles] ([Id])
GO
USE [master]
GO
ALTER DATABASE [QualityDocDB] SET  READ_WRITE 
GO
